import type { Answers, Question } from "./types";

const arrayHas = (v: unknown, target: string) => Array.isArray(v) && v.includes(target);

export const SECTIONS = [
  "Seus dados",
  "Modalidade",
  "Valores e identificação",
  "Características físicas",
  "Estrutura do imóvel",
  "Diferenciais",
  "Aspectos legais e descrição",
  "Negociação",
  "Termos e fechamento",
] as const;

export const QUESTIONS: Question[] = [
  // Seus dados
  {
    id: "nomeCompleto",
    section: "Seus dados",
    label: "Qual é o seu nome completo?",
    description: "Nome e sobrenome para o cadastro.",
    type: "text",
    placeholder: "Ex.: Maria Souza Silva",
    required: true,
  },
  {
    id: "telefone",
    section: "Seus dados",
    label: "Qual o seu telefone para contato?",
    description: "Usamos para combinar a visita e mandar atualizações da negociação.",
    type: "tel",
    placeholder: "(11) 99999-9999",
    required: true,
  },
  {
    id: "email",
    section: "Seus dados",
    label: "E o seu e-mail?",
    description: "Vamos te enviar uma cópia das informações cadastradas.",
    type: "email",
    placeholder: "voce@email.com",
    required: true,
  },
  {
    id: "enderecoImovel",
    section: "Seus dados",
    label: "Qual o endereço do imóvel?",
    description: "Endereço, bairro e CEP do imóvel que será anunciado.",
    type: "textarea",
    placeholder: "Rua, número, complemento, bairro, CEP",
    required: true,
  },

  // Modalidade
  {
    id: "cadastro",
    section: "Modalidade",
    label: "O imóvel será cadastrado para:",
    description: "Você pode marcar mais de uma opção, se aplicável.",
    type: "multi",
    options: ["Venda", "Locação", "Locação e Venda"],
    required: true,
  },
  {
    id: "temCondominio",
    section: "Modalidade",
    label: "O imóvel possui condomínio?",
    type: "single",
    options: ["Sim", "Não"],
    required: true,
  },

  // Valores e identificação
  {
    id: "iptuAnual",
    section: "Valores e identificação",
    label: "Qual o valor anual do IPTU?",
    type: "currency",
    placeholder: "R$ 0,00",
    required: true,
  },
  {
    id: "valorCondominio",
    section: "Valores e identificação",
    label: "Qual o valor mensal do condomínio?",
    type: "currency",
    placeholder: "R$ 0,00",
    required: true,
    when: (a: Answers) => a.temCondominio === "Sim",
  },
  {
    id: "valorAluguel",
    section: "Valores e identificação",
    label: "Qual o valor do aluguel?",
    description: "Mensalidade pretendida para locação.",
    type: "currency",
    placeholder: "R$ 0,00",
    required: true,
    when: (a: Answers) => arrayHas(a.cadastro, "Locação") || arrayHas(a.cadastro, "Locação e Venda"),
  },
  {
    id: "numeroIPTU",
    section: "Valores e identificação",
    label: "Qual o número do IPTU?",
    description: "Você encontra na guia anual do IPTU.",
    type: "text",
    placeholder: "Número de inscrição imobiliária",
    required: true,
  },

  // Características físicas
  {
    id: "areaTerreno",
    section: "Características físicas",
    label: "Qual a área do terreno?",
    type: "area",
    placeholder: "Ex.: 250 m²",
    required: true,
  },
  {
    id: "areaConstruida",
    section: "Características físicas",
    label: "Qual a área construída?",
    type: "area",
    placeholder: "Ex.: 180 m²",
    required: true,
  },
  {
    id: "tipoPropriedade",
    section: "Estrutura do imóvel",
    label: "Qual o tipo do imóvel?",
    description: "Marque todas as opções que descrevem o imóvel.",
    type: "multi",
    options: [
      "Apartamento",
      "Casa",
      "Casa em Condomínio",
      "Casa de vila",
      "Cobertura",
      "Comercial",
      "Duplex",
      "Flat",
      "Garden",
      "Terreno",
      "Terreno em Condomínio",
      "Studio",
      "Pousada",
    ],
    required: true,
  },
  {
    id: "andares",
    section: "Estrutura do imóvel",
    label: "Quantos andares tem o imóvel?",
    type: "single",
    options: ["Térreo", "02 pavimentos", "03 ou mais pavimentos"],
    required: true,
  },
  {
    id: "numeroSuites",
    section: "Estrutura do imóvel",
    label: "Quantas suítes o imóvel possui?",
    type: "number",
    placeholder: "Ex.: 2",
    required: true,
  },
  {
    id: "numeroQuartos",
    section: "Estrutura do imóvel",
    label: "Quantos quartos no total?",
    description: "Inclua todos os dormitórios, somando os que já são suítes.",
    type: "number",
    placeholder: "Ex.: 4",
    required: true,
  },
  {
    id: "descricaoQuartosPousada",
    section: "Estrutura do imóvel",
    label: "Descreva os quartos da pousada",
    description: "Quantos quartos, capacidade, tipo de cama, banheiros etc.",
    type: "textarea",
    placeholder: "Ex.: 6 chalés, sendo 4 com cama de casal e 2 com duas camas de solteiro...",
    required: true,
    when: (a: Answers) => arrayHas(a.tipoPropriedade, "Pousada"),
  },

  // Diferenciais
  {
    id: "caracteristicas",
    section: "Diferenciais",
    label: "Características do imóvel",
    description: "Marque tudo que se aplica.",
    type: "multi",
    options: [
      "Aquecimento Solar",
      "Aquecimento Elétrico",
      "Banheira",
      "Mobiliado",
      "Parcialmente Mobiliado",
      "Ar condicionado",
      "Para reforma",
      "Reformado",
      "Lareira",
      "Permite Animais",
    ],
    required: true,
  },
  {
    id: "comodos",
    section: "Diferenciais",
    label: "Quais cômodos o imóvel possui?",
    description: "Marque tudo que se aplica. Use o campo livre se faltar algo.",
    type: "multi",
    options: [
      "Área de serviço",
      "Home Office",
      "Cinema",
      "Lavabo",
      "Closet",
      "Varanda",
      "Despensa",
      "Varanda gourmet",
    ],
    allowOther: true,
    required: true,
  },
  {
    id: "areaExterna",
    section: "Diferenciais",
    label: "Áreas externas e de lazer",
    description: "Marque todas as áreas disponíveis no imóvel ou no condomínio.",
    type: "multi",
    options: [
      "Academia",
      "Churrasqueira",
      "Lavanderia",
      "Quadra de tênis",
      "Salão de Jogos",
      "Área Verde",
      "Coworking",
      "Piscina",
      "Quadra Esportiva",
      "Sauna",
      "Bicicletário",
      "Espaço Gourmet",
      "Piscina Aquecida",
      "Quintal",
      "SPA",
      "Brinquedoteca",
      "Estacionamento",
      "Playground",
      "Salão de Festas",
    ],
    required: true,
  },
  {
    id: "facilidades",
    section: "Diferenciais",
    label: "Facilidades e portaria",
    type: "multi",
    options: [
      "Acessibilidade",
      "Portaria Eletrônica",
      "Vaga",
      "Portaria Noturna",
      "Vaga Demarcada",
      "Portaria 24hrs",
      "Sem portaria",
    ],
    required: true,
  },

  // Aspectos legais e descrição
  {
    id: "informacoesRelevantes",
    section: "Aspectos legais e descrição",
    label: "Há outras informações relevantes sobre o imóvel?",
    description: "Opcional. Use este espaço para detalhes que ainda não foram cobertos.",
    type: "textarea",
    placeholder: "Conte o que mais quiser sobre o imóvel...",
  },
  {
    id: "escrituraDefinitiva",
    section: "Aspectos legais e descrição",
    label: "O imóvel possui escritura definitiva?",
    type: "single",
    options: ["Sim, possui escritura", "Não, possui posse"],
    required: true,
  },
  {
    id: "enderecoAnunciante",
    section: "Aspectos legais e descrição",
    label: "Qual o seu endereço residencial?",
    description: "Opcional. Pode ser diferente do endereço do imóvel.",
    type: "textarea",
    placeholder: "Endereço residencial do proprietário",
  },
  {
    id: "ramoAtividade",
    section: "Aspectos legais e descrição",
    label: "Qual o seu ramo de atividade?",
    description: "Opcional. Profissão ou área de atuação.",
    type: "text",
    placeholder: "Ex.: Empresário, médica, aposentado...",
  },
  {
    id: "descricaoImovel",
    section: "Aspectos legais e descrição",
    label: "Como você descreveria o imóvel para um possível interessado?",
    description: "Capriche: essa descrição vai ajudar a vender o imóvel.",
    type: "textarea",
    placeholder: "Conte a história do imóvel, o que o torna especial, vista, vizinhança...",
    required: true,
  },

  // Negociação
  {
    id: "garantiasLocaticias",
    section: "Negociação",
    label: "Qual garantia locatícia você aceita?",
    description: "Opcional. Só responda se vai disponibilizar para locação.",
    type: "single",
    options: ["Caução", "Fiador", "Seguro fiança", "Outros"],
    when: (a: Answers) => arrayHas(a.cadastro, "Locação") || arrayHas(a.cadastro, "Locação e Venda"),
  },
  {
    id: "ocupandoImovel",
    section: "Negociação",
    label: "Atualmente, alguém está ocupando o imóvel?",
    type: "single",
    options: [
      "Não, está desocupado",
      "Sim, o proprietário",
      "Sim, o caseiro",
      "Sim, o comerciante",
      "Locação por temporada",
      "Outros",
    ],
  },
  {
    id: "valorImovel",
    section: "Negociação",
    label: "Qual o valor pretendido na venda?",
    description: "Opcional. Só responda se vai disponibilizar para venda.",
    type: "currency",
    placeholder: "R$ 0,00",
    when: (a: Answers) => arrayHas(a.cadastro, "Venda") || arrayHas(a.cadastro, "Locação e Venda"),
  },
  {
    id: "valorLocacao",
    section: "Negociação",
    label: "Qual o valor pretendido na locação?",
    description: "Opcional, caso seja diferente do aluguel já informado.",
    type: "currency",
    placeholder: "R$ 0,00",
    when: (a: Answers) => arrayHas(a.cadastro, "Locação") || arrayHas(a.cadastro, "Locação e Venda"),
  },
  {
    id: "anoConstrucao",
    section: "Negociação",
    label: "Qual o ano de construção do imóvel?",
    description: "Opcional. Pode informar o ano aproximado.",
    type: "number",
    placeholder: "Ex.: 2015",
  },
  {
    id: "sistemaSeguranca",
    section: "Negociação",
    label: "O imóvel possui sistema de segurança?",
    type: "single",
    options: ["Sim", "Não"],
  },
  {
    id: "possuiMobilia",
    section: "Negociação",
    label: "O imóvel possui mobília?",
    type: "single",
    options: [
      "Sim, totalmente mobiliado",
      "Sim, parcialmente mobiliado",
      "Sim, deve ser anunciado com mobília",
      "Sim, parcialmente — deve ser anunciado assim",
      "Não",
      "Outros",
    ],
    required: true,
  },
  {
    id: "mobiliaParcialNaoFica",
    section: "Negociação",
    label: "Caso seja parcialmente mobiliado, o que NÃO deve ficar?",
    description: "Liste os móveis e itens que o proprietário vai retirar.",
    type: "textarea",
    placeholder: "Ex.: Geladeira, sofá da sala, cama do quarto principal...",
    when: (a: Answers) => {
      const v = a.possuiMobilia;
      return (
        v === "Sim, parcialmente mobiliado" ||
        v === "Sim, parcialmente — deve ser anunciado assim"
      );
    },
  },

  // Termos e fechamento
  {
    id: "despesasExtras",
    section: "Termos e fechamento",
    label: "Existem despesas fixas além de água, luz e IPTU?",
    description:
      "Verifique se há despesa fixa no imóvel que não esteja inclusa no aluguel. Se houver prestador de serviço vinculado (caseiro, jardineiro etc.), detalhe a função e o salário, e informe se é imprescindível para a locação.",
    type: "textarea",
    placeholder: "Detalhe aqui as despesas extras, prestadores e se são imprescindíveis...",
    required: true,
  },
  {
    id: "cotistasSocios",
    section: "Termos e fechamento",
    label: "Existe cotista, sócio ou herdeiro do imóvel?",
    description:
      "Se sim, ele está ciente da negociação, manifesta interesse em vender/locar e concorda com as informações deste formulário?",
    type: "single",
    options: [
      "Não há cotista, sócio ou herdeiro",
      "Sim, todos cientes e de acordo",
      "Sim, mas ainda preciso alinhar com eles",
    ],
    required: true,
  },
  {
    id: "chaves",
    section: "Termos e fechamento",
    label: "Como funciona o acesso às chaves?",
    type: "single",
    options: [
      "Deixarei cópia na imobiliária",
      "Precisa ser feito agendamento",
      "Outro responsável tem as chaves",
    ],
  },
  {
    id: "responsavelChaves",
    section: "Termos e fechamento",
    label: "Quem fica responsável pelas chaves na sua ausência?",
    description: "Opcional. Nome e contato (telefone/WhatsApp) do responsável.",
    type: "textarea",
    placeholder: "Ex.: João Silva — (12) 99999-9999",
  },
  {
    id: "comissaoVenda6",
    section: "Termos e fechamento",
    label: "A comissão para venda é de 6% do valor total. Você está ciente?",
    description: "Esse é o padrão de comissão praticado pela OPA Imóveis nas vendas.",
    type: "single",
    options: ["Sim, estou ciente", "Não estou ciente"],
    required: true,
  },
  {
    id: "comissaoLocacaoPrimeiro",
    section: "Termos e fechamento",
    label: "Em caso de locação, a comissão é equivalente ao primeiro aluguel. Ciente?",
    type: "single",
    options: ["Sim, estou ciente", "Não estou ciente"],
    when: (a: Answers) => arrayHas(a.cadastro, "Locação") || arrayHas(a.cadastro, "Locação e Venda"),
  },
];

export const TOTAL_QUESTIONS = QUESTIONS.length;
